# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'XSHouseLease' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XSHouseLease
   # pod 'SDWebImage'
 pod 'MJExtension'
 pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'XWAlert'
#pod 'SLEmptyView'
#pod 'SLCoreNetManage'
#pod 'SLListComponent'
pod 'AFNetworking'
pod 'MBProgressHUD', '~> 1.2.0'
pod 'YBModelFile', :configurations => ['Debug']
pod 'AESCrypt','~> 0.0.1'
pod 'BRPickerView'
pod 'HXPhotoPicker'


end
